import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

/**
 * Documentation that stays true, and a gate that keeps it that way.
 *
 * CLAUDE.md §6.11 already requires a change altering a recorded decision to
 * update `architecture.md` or add an ADR in the same pull request. Until now
 * that was etiquette: nothing checked it, so the only thing standing between
 * the repository and silent divergence — "the one unrecoverable mistake",
 * §7 — was whether the author remembered.
 *
 * Two things are asserted here. That the README's claims match the repository,
 * and that the commit-msg gate actually refuses a source change which neither
 * touches documentation nor says why it does not need to.
 */

const ROOT = join(import.meta.dirname, '..', '..')
const README = join(ROOT, 'README.md')
const HOOK = join(ROOT, '.githooks', 'commit-msg')

const git = (cwd: string, args: string[]): string =>
  execFileSync('git', args, { cwd, encoding: 'utf8', stdio: 'pipe' })

/**
 * Attempts a commit in a scratch repository with the real hook installed.
 * Returns the hook's verdict rather than throwing, so a refusal is an ordinary
 * value to assert on.
 */
function commitWith(
  repo: string,
  message: string,
  stage: Record<string, string>,
): { accepted: boolean; output: string } {
  for (const [path, content] of Object.entries(stage)) {
    const full = join(repo, path)
    mkdirSync(join(full, '..'), { recursive: true })
    writeFileSync(full, content, 'utf8')
    git(repo, ['add', path])
  }
  try {
    const output = git(repo, [
      '-c',
      'user.email=suite@example.test',
      '-c',
      'user.name=Suite',
      '-c',
      'commit.gpgsign=false',
      '-c',
      `core.hooksPath=${join(repo, '.githooks')}`,
      'commit',
      '-m',
      message,
    ])
    return { accepted: true, output }
  } catch (error) {
    const failure = error as { stdout?: Buffer | string; stderr?: Buffer | string }
    // A refused commit leaves its files staged. Without this, the next case
    // inherits them and fails for the previous case's reason — which is how a
    // suite starts reporting failures that have nothing to do with the test
    // that reported them.
    git(repo, ['reset', '--quiet'])
    for (const path of Object.keys(stage)) rmSync(join(repo, path), { force: true })
    return {
      accepted: false,
      output: `${String(failure.stdout ?? '')}${String(failure.stderr ?? '')}`,
    }
  }
}

describe('the README describes the repository as it is', () => {
  let readme: string

  beforeAll(() => {
    expect(existsSync(README), 'the repository needs a README').toBe(true)
    readme = readFileSync(README, 'utf8')
  })

  it('covers the three things a newcomer needs: what it is for, where it is, how to run it', () => {
    const headings = [...readme.matchAll(/^#{2,3}\s+(.+)$/gm)].map((m) => m[1]!.toLowerCase())
    const joined = headings.join(' | ')
    expect(joined, 'no vision section').toMatch(/vision|what .*is|why/)
    expect(joined, 'no progress section').toMatch(/progress|status|where .*is|state/)
    expect(joined, 'no run instructions').toMatch(/run|start|quick/)
  })

  it('shows only commands that exist', () => {
    // A README whose first command does not work costs a newcomer more
    // goodwill than everything below it earns back.
    const scripts = Object.keys(
      (JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
        scripts: Record<string, string>
      }).scripts,
    )
    const used = [...readme.matchAll(/\bpnpm (?:run )?([a-z][a-z:-]*)/g)].map((m) => m[1]!)
    expect(used.length, 'the README should show how to run something').toBeGreaterThan(0)
    for (const script of used) {
      if (['install', 'dlx', 'add'].includes(script)) continue
      expect(scripts, `README runs "pnpm ${script}" but package.json has no such script`).toContain(
        script,
      )
    }
  })

  it('links only to files that exist', () => {
    const links = [...readme.matchAll(/\]\((?!https?:|#)([^)]+)\)/g)].map((m) => m[1]!)
    expect(links.length, 'the README should point somewhere').toBeGreaterThan(0)
    for (const link of links) {
      const target = join(ROOT, link.split('#')[0]!)
      expect(existsSync(target), `README links ${link}, which does not exist`).toBe(true)
    }
  })

  it('states progress from generated figures rather than remembered ones', () => {
    // Delimited like CONTRIBUTING.md's quick-start block, and regenerated by
    // `pnpm docs:sync`, so the numbers cannot quietly drift from the code.
    const block = readme.split('<!-- progress -->')[1]?.split('<!-- /progress -->')[0]
    expect(block, 'README must delimit its generated progress block').toBeDefined()

    const status = JSON.parse(
      readFileSync(join(ROOT, 'website', 'src', 'status.json'), 'utf8'),
    ) as {
      tests: { total: number }
      routes: unknown[]
      requirements: { total: number; withPassingTests: number }
    }

    expect(block).toContain(String(status.tests.total))
    expect(block).toContain(String(status.routes.length))
    expect(block).toContain(String(status.requirements.total))
    expect(block).toContain(String(status.requirements.withPassingTests))
  })

  it('does not promise more of a user interface than exists', () => {
    // The claim in the README is "the interface is one screen". That stays
    // true only while it is, so the screens are counted rather than trusted.
    expect(
      screens(),
      'a screen was added or removed — say so in the README status line',
    ).toEqual(SCREENS_TODAY)

    // Markdown syntax stripped before matching: the claim is wrapped across
    // lines inside a blockquote, so emphasis markers and `>` land in the middle
    // of the sentence. A check that only matched the unwrapped form would pass
    // or fail on how the paragraph happened to be reflowed.
    const flat = readme
      .toLowerCase()
      .replace(/[*_`>#]/g, '')
      .replace(/\s+/g, ' ')
    expect(flat).toMatch(/interface is one screen|no (user interface|web (app|interface))/)
  })
})

describe('the documentation gate', () => {
  let repo: string

  beforeAll(() => {
    expect(existsSync(HOOK), 'a commit-msg hook must exist').toBe(true)

    repo = mkdtempSync(join(tmpdir(), 'chorus-gate-'))
    git(repo, ['init', '--quiet'])
    mkdirSync(join(repo, '.githooks'), { recursive: true })
    writeFileSync(join(repo, '.githooks', 'commit-msg'), readFileSync(HOOK, 'utf8'), {
      encoding: 'utf8',
      mode: 0o755,
    })

    // A first commit, so later ones have a parent and `git diff --cached`
    // behaves as it does in a real repository.
    commitWith(repo, 'chore: initial\n\nDocs: none — repository skeleton only.', {
      'README.md': '# scratch\n',
    })
  }, 60_000)

  afterAll(() => {
    if (repo) rmSync(repo, { recursive: true, force: true })
  })

  it('is executable in the index, or git will silently ignore it on clone', () => {
    // A hook without the execute bit does not fail loudly; it simply never
    // runs, which is the worst possible behaviour for a gate.
    //
    // Asserted against git's recorded mode rather than the filesystem's:
    // Windows checkouts have no execute bit to report, so a filesystem check
    // would fail on Windows and — worse — pass on Linux even if the mode had
    // never been committed. The index mode is what reaches everyone else.
    const entry = execFileSync('git', ['ls-files', '--stage', '.githooks/commit-msg'], {
      cwd: ROOT,
      encoding: 'utf8',
    })
    expect(entry.trim(), '.githooks/commit-msg must be committed as mode 100755').toMatch(
      /^100755 /,
    )
  })

  it('is installed for everyone by `pnpm install`, not by a step people must remember', () => {
    const packageJson = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
      scripts: Record<string, string>
    }
    expect(packageJson.scripts.prepare).toContain('core.hooksPath')
  })

  it('refuses a source change that neither documents itself nor says why it need not', () => {
    const result = commitWith(repo, 'feat(api): add a route', {
      'apps/api/src/routes.ts': 'export const added = true\n',
    })
    expect(result.accepted, 'an undocumented source change was allowed through').toBe(false)
    expect(result.output).toMatch(/Docs:/)
  })

  it('accepts a source change that updates documentation alongside it', () => {
    const result = commitWith(repo, 'feat(api): add another route', {
      'apps/api/src/other.ts': 'export const other = true\n',
      'architecture.md': '# architecture\n\nThe other route exists.\n',
    })
    expect(result.accepted, result.output).toBe(true)
  })

  it('accepts a source change whose message records why no documentation changed', () => {
    // The escape hatch is deliberate and recorded in history, rather than
    // silent. "No documentation needed" becomes a claim someone made and a
    // reviewer can disagree with.
    const result = commitWith(
      repo,
      'refactor(api): extract a helper\n\nDocs: none — pure extraction, no recorded decision changed.',
      { 'apps/api/src/helper.ts': 'export const helper = true\n' },
    )
    expect(result.accepted, result.output).toBe(true)
  })

  it('refuses a justification too short to be one', () => {
    // Without this the gate is defeated by `Docs: n/a`, and a gate that is
    // trivially defeated teaches people to defeat it.
    const result = commitWith(repo, 'refactor(api): tidy\n\nDocs: n/a', {
      'apps/api/src/tidy.ts': 'export const tidy = true\n',
    })
    expect(result.accepted, 'a token justification was accepted').toBe(false)
  })

  it('leaves non-source commits alone', () => {
    const result = commitWith(repo, 'chore: add a fixture', {
      'test/fixtures/example.json': '{}\n',
    })
    expect(result.accepted, result.output).toBe(true)
  })

  it('exempts merges and reverts, which have no documentation of their own to write', () => {
    const merge = commitWith(repo, 'Merge branch “topic” into main', {
      'apps/api/src/merged.ts': 'export const merged = true\n',
    })
    expect(merge.accepted, merge.output).toBe(true)

    const revert = commitWith(repo, 'Revert "feat(api): add another route"', {
      'apps/api/src/reverted.ts': 'export const reverted = true\n',
    })
    expect(revert.accepted, revert.output).toBe(true)
  })

  it('explains what to do rather than only saying no', () => {
    const result = commitWith(repo, 'feat(db): a migration', {
      'packages/db/migrations/0099_example.sql': 'SELECT 1;\n',
    })
    expect(result.accepted, 'a migration is a recorded decision').toBe(false)
    expect(result.output, 'the refusal must name the documents it will accept').toMatch(
      /architecture\.md|docs\/adr/,
    )
  })
})

/**
 * Every screen the web app actually has.
 *
 * Derived from the filesystem rather than listed, so adding a page fails this
 * test and whoever added it has to say so in the prose. The original version of
 * this gate asserted that `apps/web` did not exist, which was true for exactly
 * as long as it took somebody to build one — and a gate that can only hold
 * while nothing happens is not a gate.
 */
function screens(): string[] {
  const root = join(ROOT, 'apps', 'web', 'src', 'app')
  if (!existsSync(root)) return []

  const found: string[] = []
  const walk = (directory: string, route: string): void => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        walk(join(directory, entry.name), `${route}/${entry.name}`)
      } else if (entry.name === 'page.tsx') {
        found.push(route === '' ? '/' : route)
      }
    }
  }
  walk(root, '')
  return found.sort()
}

const SCREENS_TODAY = ['/', '/workspaces/[workspaceId]/documents/[documentId]']
