import { it } from 'vitest'
import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { createIsolatedDatabase } from '@chorus/db'
import { createApp } from '@chorus/api'
import { createRecordingMailer, createTestClient } from '@chorus/testing'

/**
 * Records real API transcripts for the project website.
 *
 * The site shows what Chorus actually does today, and there is no UI yet — so
 * rather than mock up screens that do not exist, this drives the real
 * application over real HTTP against a real Postgres and records exactly what
 * came back. Every transcript on the site is generated by this file; if a
 * response changes, the site changes with it, and a claim the code stops
 * supporting cannot quietly survive.
 */

interface Exchange {
  readonly title: string
  readonly note: string
  readonly steps: ReadonlyArray<{
    readonly method: string
    readonly path: string
    readonly as: string
    readonly status: number
    readonly body?: unknown
    readonly response: unknown
  }>
}

const OUT = join(import.meta.dirname, '..', 'src', 'transcripts.json')

it('records API transcripts for the website', async () => {
  const db = await createIsolatedDatabase()
  const mailer = createRecordingMailer()
  const client = createTestClient(createApp({ dbConfig: db.config, mailer }), mailer)

  const exchanges: Exchange[] = []
  const readJson = async (response: Response): Promise<unknown> => {
    const text = await response.text()
    if (!text) return null
    try {
      return JSON.parse(text)
    } catch {
      return text
    }
  }

  try {
    // ---------------------------------------------------------------------
    // 1. Sign up, and get a workspace that is usable immediately.
    // ---------------------------------------------------------------------
    const ada = await client.signedInUser('ada@example.test')
    const created = await ada.post('/workspaces', { name: 'Acme Product' })
    const workspace = (await created.clone().json()) as { id: string }

    const teamsResponse = await ada.get(`/workspaces/${workspace.id}/teams`)
    const teams = (await teamsResponse.clone().json()) as Array<{ id: string }>
    const teamId = teams[0]!.id

    exchanges.push({
      title: 'A new workspace is usable immediately',
      note: 'Creating a workspace makes the creator its owner and seeds exactly one team, so there is no empty-state setup step before the first piece of work.',
      steps: [
        {
          method: 'POST',
          path: '/workspaces',
          as: 'ada (signed in)',
          status: created.status,
          body: { name: 'Acme Product' },
          response: await readJson(created),
        },
        {
          method: 'GET',
          path: `/workspaces/{id}/teams`,
          as: 'ada (owner)',
          status: teamsResponse.status,
          response: await readJson(teamsResponse),
        },
      ],
    })

    // ---------------------------------------------------------------------
    // 2. The charter — the cheapest lever on agent output quality.
    // ---------------------------------------------------------------------
    const charter = await ada.patch(`/workspaces/${workspace.id}/teams/${teamId}`, {
      charter: '# Mission\n\nWe own money movement.\n\nNever guess at a currency conversion.',
    })
    const oversized = await ada.post(`/workspaces/${workspace.id}/teams`, {
      name: 'Verbose',
      charter: 'x'.repeat(8001),
    })

    exchanges.push({
      title: 'Every team carries a charter',
      note: 'The charter is injected into every agent prompt, so it is bounded — and an oversized one is refused rather than truncated, because a charter cut off mid-sentence is a corrupted instruction rather than a long one.',
      steps: [
        {
          method: 'PATCH',
          path: '/workspaces/{id}/teams/{teamId}',
          as: 'ada (owner)',
          status: charter.status,
          body: { charter: '# Mission\n\nWe own money movement. …' },
          response: await readJson(charter),
        },
        {
          method: 'POST',
          path: '/workspaces/{id}/teams',
          as: 'ada (owner)',
          status: oversized.status,
          body: { name: 'Verbose', charter: '"x" × 8001' },
          response: await readJson(oversized),
        },
      ],
    })

    // ---------------------------------------------------------------------
    // 3. Checkpoint policy: whether an autonomous step stops and asks.
    // ---------------------------------------------------------------------
    const workflowDefault = await ada.put(`/workspaces/${workspace.id}/policies`, {
      workflowName: 'implement-task',
      checkpointKind: 'before_external_write',
      mode: 'auto',
    })
    const teamOverride = await ada.put(
      `/workspaces/${workspace.id}/teams/${teamId}/policies`,
      { checkpointKind: 'before_external_write', mode: 'ask' },
    )
    const resolved = await ada.get(
      `/workspaces/${workspace.id}/teams/${teamId}/policies?workflow=implement-task`,
    )

    exchanges.push({
      title: 'Humans hold the gates',
      note: 'A checkpoint policy decides whether an autonomous step runs unattended. Resolution runs team → workflow → platform, and the platform default is `ask`: it fails closed, so an unconfigured workspace is never autonomous by omission. Each answer names the tier that decided it.',
      steps: [
        {
          method: 'PUT',
          path: '/workspaces/{id}/policies',
          as: 'ada (owner)',
          status: workflowDefault.status,
          body: { workflowName: 'implement-task', checkpointKind: 'before_external_write', mode: 'auto' },
          response: await readJson(workflowDefault),
        },
        {
          method: 'PUT',
          path: '/workspaces/{id}/teams/{teamId}/policies',
          as: 'ada (owner)',
          status: teamOverride.status,
          body: { checkpointKind: 'before_external_write', mode: 'ask' },
          response: null,
        },
        {
          method: 'GET',
          path: '/workspaces/{id}/teams/{teamId}/policies?workflow=implement-task',
          as: 'ada (owner)',
          status: resolved.status,
          response: await readJson(resolved),
        },
      ],
    })

    // ---------------------------------------------------------------------
    // 4. Permissions, and the shape of a refusal.
    // ---------------------------------------------------------------------
    const grace = await client.memberWithRole(ada, workspace.id, 'member', 'grace@example.test')
    const refused = await grace.post(`/workspaces/${workspace.id}/teams`, { name: 'Mine' })
    const permitted = await grace.get(`/workspaces/${workspace.id}/teams`)

    const stranger = await client.signedInUser('stranger@example.test')
    const notFound = await stranger.get(`/workspaces/${workspace.id}/teams`)

    exchanges.push({
      title: 'Refusals are specific, and absence is not information',
      note: 'A member may read a team but not create one, and the refusal says what was required and what was held. A non-member is answered not-found rather than forbidden — confirming that a workspace exists would let anyone enumerate them by id.',
      steps: [
        {
          method: 'GET',
          path: '/workspaces/{id}/teams',
          as: 'grace (member)',
          status: permitted.status,
          response: '[ … the teams grace may read … ]',
        },
        {
          method: 'POST',
          path: '/workspaces/{id}/teams',
          as: 'grace (member)',
          status: refused.status,
          body: { name: 'Mine' },
          response: await readJson(refused),
        },
        {
          method: 'GET',
          path: '/workspaces/{id}/teams',
          as: 'stranger (not a member)',
          status: notFound.status,
          response: await readJson(notFound),
        },
      ],
    })

    // ---------------------------------------------------------------------
    // 5. The audit trail, written in the same transaction as the change.
    // ---------------------------------------------------------------------
    const events = await db.admin.query<{ action: string; actor_id: string; target_type: string }>(
      `SELECT action, actor_id, target_type FROM audit_events
        WHERE workspace_id = $1 ORDER BY at`,
      [workspace.id],
    )

    exchanges.push({
      title: 'Everything is auditable',
      note: 'Every mutation writes its audit row in the same transaction as the change itself, so there is no change without a record and no record without a change. Refusals are recorded too — a misconfigured permission is otherwise an unexplained 403 that nobody can tell was correct.',
      steps: [
        {
          method: 'SQL',
          path: 'SELECT action, actor_id, target_type FROM audit_events',
          as: 'the workspace trail',
          status: 200,
          response: events.map((event) => ({
            action: event.action,
            actor: event.actor_id ? `${event.actor_id.slice(0, 8)}…` : null,
            target: event.target_type,
          })),
        },
      ],
    })

    mkdirSync(join(import.meta.dirname, '..', 'src'), { recursive: true })
    writeFileSync(OUT, `${JSON.stringify({ exchanges }, null, 2)}\n`, 'utf8')
    console.log(`recorded ${exchanges.length} exchanges to ${OUT}`)
  } finally {
    await db.drop()
  }
})
